### ISSUE TITLE
bug(bigquery): returns unnestted array value and its offset as a struct

### ISSUE THREAD

**Issue by chelsea-lin** [tobymao/sqlglot#2978]
**Fully reproducible code snippet**
I tried to return unnestted array value and its offset and combine them as a struct. However, only the value is included in the struct but the offset is excluded. 

Here is the reproducible code: 

```
In [3]: import sqlglot as sg
   ...: query = "SELECT (SELECT AS STRUCT POSEXPLODE(X)) FROM bigframes-dev.ibis_gbq_testing.array_types"
   ...: tree = sg.parse_one(query, dialect='bigquery')

In [4]: tree
Out[4]: 
Select(
  expressions=[
    Subquery(
      this=Select(
        kind=STRUCT,
        expressions=[
          Posexplode(
            this=Column(
              this=Identifier(this=X, quoted=False)))]))],
  from=From(
    this=Table(
      this=Identifier(this=array_types, quoted=False),
      db=Identifier(this=ibis_gbq_testing, quoted=False),
      catalog=Identifier(this=bigframes-dev, quoted=False))))

In [5]: tree.sql(dialect='bigquery')
Out[5]: 'SELECT (SELECT AS STRUCT IF(pos = pos_2, col, NULL)) AS col, IF(pos = pos_2, pos_2, NULL) AS pos_2 FROM bigframes-dev.ibis_gbq_testing.array_types CROSS JOIN UNNEST(GENERATE_ARRAY(0, GREATEST(ARRAY_LENGTH(X)) - 1)) AS pos CROSS JOIN UNNEST(X) AS col WITH OFFSET AS pos_2 WHERE pos = pos_2 OR (pos > (ARRAY_LENGTH(X) - 1) AND pos_2 = (ARRAY_LENGTH(X) - 1))'
```

My expectation for the result would be as below (where `)` is moved from before `AS col` to before `FROM`)
```
Out[5]: 'SELECT (SELECT AS STRUCT IF(pos = pos_2, col, NULL) AS col, IF(pos = pos_2, pos_2, NULL) AS pos_2) FROM bigframes-dev.ibis_gbq_testing.array_types CROSS JOIN UNNEST(GENERATE_ARRAY(0, GREATEST(ARRAY_LENGTH(X)) - 1)) AS pos CROSS JOIN UNNEST(X) AS col WITH OFFSET AS pos_2 WHERE pos = pos_2 OR (pos > (ARRAY_LENGTH(X) - 1) AND pos_2 = (ARRAY_LENGTH(X) - 1))'
```

Is this request reasonable? If so, I would like to help contributing also. If not, do we have any workaround solution to meet my requirements? I

**Comment by georgesittas** [comment]
Hey @chelsea-lin, what dialect does the input query correspond to? I don't think BigQuery supports `POSEXPLODE`? I'd assume that your query is written in something like Spark SQL but that then `SELECT AS STRUCT` would be invalid. Can you provide some more context?

**Comment by tobymao** [comment]
closing this for now but happy to address if more details are added.

**Comment by chelsea-lin** [comment]
Sorry for the late reply - I was offline for a bit. Thanks for the correction, @georgesittas. 
The original post had a typo, which is now fixed. My primary goal is to use `sqlglot.transpile` to convert a Spark query with `POSEXPODE(array)` to BigQuery. In the process, I want to create a struct containing each unnested array element and its offset.

**Comment by chelsea-lin** [comment]
kindly ping the thread, as I am still waiting for the answer of this thread. Thanks!

**Comment by georgesittas** [comment]
Hey @chelsea-lin, thanks for bumping the thread.

Can you please provide a valid spark query so I can test this? Ideally, a self-contained test case (i.e. using statically defined data). Correct me if I'm wrong, but the edited example still doesn't seem to be valid spark SQL:

```
spark-sql (default)> WITH table(X) AS (SELECT ARRAY(1,2,3,4)) SELECT (SELECT STRUCT (POSEXPLODE(X)) AS unnested) FROM table;
[UNSUPPORTED_GENERATOR.NESTED_IN_EXPRESSIONS] The generator is not supported: nested in expressions "struct(posexplode(outer(table.X)))".
```

**Comment by chelsea-lin** [comment]
Thanks @georgesittas for the clarification. My initial request was coming from a request of the `ibis` library, which relies on the `explode_to_unnest` function to generate expression tree for BigQuery `unnest` function. I didn't initially consider the equality API is not a standard API for sqlglot user. I'll keep the issue closed. Thanks for your time!
